#! /bin/sh

chosen=$(printf "  Power Off\n  Restart\n  Sleep" | rofi -dmenu -i -theme-str '@import "power.rasi"')

case "$chosen" in
	"  Power Off") poweroff ;;
	"  Restart") shutdown -r now ;;
	"  Sleep") systemctl suspend ;;
	*) exit 1 ;;
esac
